version: '3.8'

services:
  user-manager:
    build:
      context: .
      dockerfile: Dockerfile.user-manager
    container_name: prpl-user-manager
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user_instances:/app/user_instances
    ports:
      - "8000:8000"
    networks:
      - prpl-main-network
    restart: unless-stopped

  nginx:
    image: nginx:1.21
    container_name: prpl-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - prpl-main-network
    restart: unless-stopped
    depends_on:
      - user-manager

networks:
  prpl-main-network:
    driver: bridge
