#version: '3.8'  # This is marked as obsolete but isn't causing failure

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: prpl-app-${USER_ID}
    environment:
      - NEO4J_URI=bolt://neo4j-${USER_ID}:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CODE_BASE_PATH=/app/code
      - USER_ID=${USER_ID}
      - PORT=5001
    volumes:
      - ./code:/app/code
      - ./vector_stores_${USER_ID}:/app/vector_stores
    networks:
      - prpl_network
    restart: unless-stopped
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.13.0
    container_name: neo4j-${USER_ID}
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - ./neo4j_data_${USER_ID}:/data
    networks:
      - prpl_network
    restart: unless-stopped

networks:
  prpl_network:
    name: prpl-network-${USER_ID}
    driver: bridge
